"""Generate HDF5 files with RGB images + optional DA3 depth images.

Depth images are expected to be generated by Depth Anything 3,
which saves them as {frame_id}_da3.png next to the original {frame_id}.png.

Usage:
    python data/generate_hdf5.py \
        --task_name pick_cube_letter \
        --root_dir /path/to/raw_episodes \
        --target_dir /path/to/output/processed_rdt2 \
        --epsd_json /path/to/episode_instructions.json \
        --config_path configs/demo.yaml

    # Skip depth images:
    python data/generate_hdf5.py ... --no-depth

    # For Franka robot data (swaps left/right cameras):
    python data/generate_hdf5.py ... --is-franka

    # Filter recovery actions for specific episodes:
    python data/generate_hdf5.py ... --filter-recovery
"""

import os
import re
import json
import argparse
import multiprocessing as mp
from multiprocessing import Pool

import h5py
import yaml
from tqdm import tqdm
import numpy as np
from PIL import Image


# Regex: match "{number}.png" but NOT "{number}_da3.png" or similar
_ORIG_PNG_RE = re.compile(r"^(\d+)\.png$")
# Regex: match "{number}_da3.png" but NOT "{number}_da3_da3.png"
_DEPTH_PNG_RE = re.compile(r"^(\d+)_da3\.png$")


def png_to_array(image_path):
    """Convert original PNG images (not depth) in a directory to numpy array."""
    files = os.listdir(image_path)
    images = [f for f in files if _ORIG_PNG_RE.match(f)]
    images = sorted(images, key=lambda x: int(x.split(".")[0]))
    image_arr = []
    for img in images:
        img_path = os.path.join(image_path, img)
        img_data = Image.open(img_path).convert("RGB")
        image_arr.append(np.array(img_data))
    image_arr = np.stack(image_arr, axis=0)
    return image_arr


def depth_png_to_array(image_path):
    """Load DA3 depth images ({number}_da3.png) from a directory.

    Returns:
        np.ndarray of shape (N, H, W, 3), uint8 (colorized depth from DA3)
    """
    files = os.listdir(image_path)
    depth_files = [f for f in files if _DEPTH_PNG_RE.match(f)]
    if not depth_files:
        raise FileNotFoundError(
            f"No DA3 depth images (*_da3.png) found in {image_path}. "
            f"Run Depth Anything 3 on this directory first."
        )
    depth_files = sorted(depth_files, key=lambda x: int(_DEPTH_PNG_RE.match(x).group(1)))

    image_arr = []
    for f in depth_files:
        img_path = os.path.join(image_path, f)
        img_data = Image.open(img_path).convert("RGB")
        image_arr.append(np.array(img_data))
    image_arr = np.stack(image_arr, axis=0)
    return image_arr


def filter_still_frames(proprio, threshold=0.005):
    """Filter out still frames at the beginning and end of the sequence."""
    left_eef_indices = slice(0, 3)
    right_eef_indices = slice(7, 10)

    n_frames = proprio.shape[0]
    if n_frames <= 2:
        raise ValueError("Not enough frames to filter still frames.")

    start_idx = 0
    first_frame = proprio[0]
    for i in range(1, n_frames):
        left_dist = np.linalg.norm(proprio[i, left_eef_indices] - first_frame[left_eef_indices])
        right_dist = np.linalg.norm(proprio[i, right_eef_indices] - first_frame[right_eef_indices])
        if left_dist > threshold or right_dist > threshold:
            break
        start_idx = i

    end_idx = n_frames - 1
    last_frame = proprio[-1]
    for i in range(n_frames - 2, start_idx, -1):
        left_dist = np.linalg.norm(proprio[i, left_eef_indices] - last_frame[left_eef_indices])
        right_dist = np.linalg.norm(proprio[i, right_eef_indices] - last_frame[right_eef_indices])
        if left_dist > threshold or right_dist > threshold:
            break
        end_idx = i

    kept_indices = [0] + list(range(start_idx + 1, end_idx)) + [n_frames - 1]
    filtered_len = n_frames - len(kept_indices)
    return kept_indices, filtered_len


def process_episode(args):
    """Process a single episode and return action statistics."""
    episode, root_dir, target_task_dir, epsd_idx, no_depth, is_franka, filter_recovery, cfg = args

    try:
        episode_path = os.path.join(root_dir, episode)
        raw_data = np.load(os.path.join(episode_path, "raw_actions.npy"))

        if raw_data.shape[0] < 32:
            print(f"Skipping episode {episode} due to insufficient length.")
            return None

        # ==================== Load RGB images ====================
        left_cam_path = os.path.join(episode_path, "left_stereo")
        left_cam_images = png_to_array(left_cam_path)

        right_cam_path = os.path.join(episode_path, "right_stereo")
        right_cam_images = png_to_array(right_cam_path)

        # ==================== Load DA3 depth images ====================
        if not no_depth:
            left_depth_images = depth_png_to_array(left_cam_path)
            right_depth_images = depth_png_to_array(right_cam_path)

            assert left_cam_images.shape[0] == left_depth_images.shape[0], (
                f"Episode {episode}: left RGB ({left_cam_images.shape[0]}) vs "
                f"depth ({left_depth_images.shape[0]}) frame count mismatch"
            )
            assert right_cam_images.shape[0] == right_depth_images.shape[0], (
                f"Episode {episode}: right RGB ({right_cam_images.shape[0]}) vs "
                f"depth ({right_depth_images.shape[0]}) frame count mismatch"
            )

        # Franka has a swapped left-right camera order
        if is_franka:
            left_cam_images, right_cam_images = right_cam_images, left_cam_images
            if not no_depth:
                left_depth_images, right_depth_images = right_depth_images, left_depth_images

        # Compensate latency for camera
        camera_latency_frames = cfg["common"]["camera_obs_latency_frames"]
        if camera_latency_frames > 0:
            left_cam_images = left_cam_images[camera_latency_frames:]
            right_cam_images = right_cam_images[camera_latency_frames:]
            if not no_depth:
                left_depth_images = left_depth_images[camera_latency_frames:]
                right_depth_images = right_depth_images[camera_latency_frames:]
            raw_data = raw_data[:-camera_latency_frames]

        # Split raw data into states and actions
        proprio = raw_data[:-1]
        action = raw_data[1:]

        # Filter recovery actions
        if filter_recovery and episode.startswith("20250819_"):
            proprio = proprio[75:]
            action = action[75:]
            left_cam_images = left_cam_images[75:]
            right_cam_images = right_cam_images[75:]
            if not no_depth:
                left_depth_images = left_depth_images[75:]
                right_depth_images = right_depth_images[75:]

        # Filter still frames
        kept_indices, filtered_len = filter_still_frames(proprio)
        if filtered_len > 0:
            proprio = proprio[kept_indices]
            action = action[kept_indices]
            left_cam_images = left_cam_images[kept_indices]
            right_cam_images = right_cam_images[kept_indices]
            if not no_depth:
                left_depth_images = left_depth_images[kept_indices]
                right_depth_images = right_depth_images[kept_indices]

        # ==================== Write HDF5 ====================
        new_file_path = os.path.join(target_task_dir, f"episode_{epsd_idx}.hdf5")
        with h5py.File(new_file_path, "w") as new_f:
            new_f.create_dataset("action", data=action)
            obs_group = new_f.create_group("observations")

            images_group = obs_group.create_group("images")
            images_group.create_dataset("left_stereo", data=left_cam_images)
            images_group.create_dataset("right_stereo", data=right_cam_images)

            if not no_depth:
                depth_group = obs_group.create_group("depth_images")
                depth_group.create_dataset("left_stereo", data=left_depth_images)
                depth_group.create_dataset("right_stereo", data=right_depth_images)

            obs_group.create_dataset("state", data=proprio)

        action_stats = {
            'count': action.shape[0],
            'sum': np.sum(action, axis=0),
            'max': np.max(action, axis=0),
            'min': np.min(action, axis=0),
            'sq_sum': np.sum(action ** 2, axis=0),
        }

        return action_stats, epsd_idx, episode, filtered_len

    except Exception as e:
        print(f"Error processing episode {episode}: {str(e)}")
        import traceback
        traceback.print_exc()
        return None


def merge_action_stats(stats_list):
    """Merge action statistics from multiple episodes."""
    valid_stats = [s for s in stats_list if s is not None]
    if not valid_stats:
        raise RuntimeError("No valid episodes processed.")

    first_stat = valid_stats[0][0]

    total_count = 0
    total_sum = np.zeros_like(first_stat['sum'])
    total_max = np.full_like(first_stat['max'], float('-inf'))
    total_min = np.full_like(first_stat['min'], float('inf'))
    total_sq_sum = np.zeros_like(first_stat['sq_sum'])
    min_filtered_len = min([s[3] for s in valid_stats])
    max_filtered_len = max([s[3] for s in valid_stats])

    for stat_tuple in valid_stats:
        stat = stat_tuple[0]
        total_count += stat['count']
        total_sum += stat['sum']
        total_max = np.maximum(total_max, stat['max'])
        total_min = np.minimum(total_min, stat['min'])
        total_sq_sum += stat['sq_sum']

    action_mean = total_sum / total_count
    action_std = np.sqrt(np.maximum(total_sq_sum / total_count - action_mean ** 2, 0))

    return {
        'count': total_count,
        'mean': action_mean,
        'std': action_std,
        'max': total_max,
        'min': total_min,
    }, min_filtered_len, max_filtered_len


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate HDF5 files with RGB (and optionally depth) images."
    )
    parser.add_argument("--task_name", type=str, required=True,
                        help="Task name (e.g. pick_cube_letter, fold, unzip).")
    parser.add_argument("--root_dir", type=str, required=True,
                        help="Root directory containing raw episode folders.")
    parser.add_argument("--target_dir", type=str, required=True,
                        help="Output directory for processed HDF5 files.")
    parser.add_argument("--epsd_json", type=str, required=True,
                        help="Path to JSON file mapping episode names to instructions.")
    parser.add_argument("--config_path", type=str, default="configs/demo.yaml",
                        help="Path to the YAML config file.")
    parser.add_argument("--no-depth", action="store_true",
                        help="Skip loading and saving DA3 depth images.")
    parser.add_argument("--is-franka", action="store_true",
                        help="Swap left/right cameras (Franka has reversed camera order).")
    parser.add_argument("--filter-recovery", action="store_true",
                        help="Filter recovery actions for specific episodes.")
    parser.add_argument("--num_workers", type=int, default=64,
                        help="Maximum number of parallel workers.")
    args = parser.parse_args()

    # Load config
    cfg = yaml.safe_load(open(args.config_path, "r"))

    # Load episode-to-instruction mapping
    epsd_json = json.load(open(args.epsd_json, "r"))

    if os.path.exists(args.target_dir):
        print(f"Target directory {args.target_dir} already exists. Please remove it before generating new data.")
        exit(1)
    os.makedirs(args.target_dir)
    target_task_dir = os.path.join(args.target_dir, args.task_name)
    os.makedirs(target_task_dir)

    # Extract language instruction
    instruction = list(epsd_json.values())[0]
    instructions = [instruction]
    with open(os.path.join(target_task_dir, "instructions.json"), "w") as f:
        json.dump(instructions, f, indent=4)

    episode_names = sorted(epsd_json.keys())
    print(f"Found {len(episode_names)} episodes to process")

    # Prepare arguments for multiprocessing
    process_args = []
    for epsd_idx, episode in enumerate(episode_names):
        process_args.append((
            episode, args.root_dir, target_task_dir, epsd_idx,
            args.no_depth, args.is_franka, args.filter_recovery, cfg,
        ))

    num_processes = min(args.num_workers, len(episode_names))
    print(f"Using {num_processes} processes")

    # Process episodes in parallel
    with Pool(processes=num_processes) as pool:
        results = list(tqdm(
            pool.imap(process_episode, process_args),
            total=len(process_args),
            desc="Processing episodes",
        ))

    # Merge action statistics
    print("Merging action statistics...")
    final_stats, min_filtered_len, max_filtered_len = merge_action_stats(results)

    print(f"Action Count: {final_stats['count']}")
    print(f"Action Mean Shape: {final_stats['mean'].shape}")
    print(f"Action Std Shape: {final_stats['std'].shape}")
    print(f"Action Max Shape: {final_stats['max'].shape}")
    print(f"Action Min Shape: {final_stats['min'].shape}")
    print("-" * 40)
    print(f"Minimum Filtered Length: {min_filtered_len}")
    print(f"Maximum Filtered Length: {max_filtered_len}")

    # Save statistics
    action_stats = {
        "action_count": int(final_stats['count']),
        "action_mean": final_stats['mean'].tolist(),
        "action_std": final_stats['std'].tolist(),
        "action_max": final_stats['max'].tolist(),
        "action_min": final_stats['min'].tolist(),
    }
    with open(os.path.join(args.target_dir, "action_stats.json"), "w") as f:
        json.dump(action_stats, f, indent=4)

    print("Processing completed successfully!")
